# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: backend

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        working-directory: backend

      - name: 빌드된 파일 이름 변경하기
        run: |
          JAR_FILE=$(ls ./build/libs/backend-*.jar | grep -v plain | head -n 1)
          mv "$JAR_FILE" ./build/libs/app.jar
        working-directory: backend

      - name: 빌드된 파일 있는지 확인
        run: ls ./build/libs
        working-directory: backend

      - name: 빌드된 파일 전송하기
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: backend/build/libs/app.jar
          target: /home/ubuntu/data/jjust.kr

      - name: 전송받은 파일 Docker 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd data
            ./jjust-down-up.sh